Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,8 @@
-name: Toffee Instant Sync
+name: Toffee Private Smart Loop
 
 on:
   schedule:
-    - cron: '*/5 * * * *'
+    - cron: '0 0 * * *' 
   workflow_dispatch:      
   push:
     paths:
@@ -32,15 +32,41 @@ jobs:
           python3 tmp_script/tf.py
           rm -rf tmp_script
 
-      - name: Push
+      - name: Push and Set Delay
+        id: check_update
         run: |
           git config --global user.name "Asim Dipto"
           git config --global user.email "asimdipto@github.com"
           git add .
           if git diff --staged --quiet; then
-            echo "No change detected."
+            echo "updated=false" >> $GITHUB_OUTPUT
           else
             git commit -m "Auto Sync: $(date +'%H:%M:%S')"
             git pull origin main --rebase
             git push origin main
+            echo "updated=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Smart Loop Trigger
+        run: |
+          HOUR=$(date -u +%H)
+          MIN=$(date -u +%M)
+          
+          # Sleep logic (12:30 AM to 6:00 AM BD Time)
+          if [ "$HOUR" -eq 18 ] && [ "$MIN" -ge 30 ] || [ "$HOUR" -gt 18 ] || [ "$HOUR" -lt 0 ]; then
+              echo "Night time. Stop."
+          else
+              # Update paile 50 min wait, na paile 15 min wait
+              if [ "${{ steps.check_update.outputs.updated }}" = "true" ]; then
+                echo "Update done. Sleeping for 50 minutes..."
+                sleep 3000
+              else
+                echo "No update. Checking again in 15 minutes..."
+                sleep 900
+              fi
+
+              curl -X POST -H "Authorization: token ${{ secrets.MY_PAT_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/actions/workflows/toffee_update.yml/dispatches \
+              -d '{"ref":"main"}' || echo "Failed"
           fi
